/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PredictionInput = IDL.Record({
  'systolic_avg_7d' : IDL.Opt(IDL.Float64),
  'diastolic_latest' : IDL.Opt(IDL.Float64),
  'diastolic_avg_14d' : IDL.Opt(IDL.Float64),
  'sleep_avg_7d' : IDL.Opt(IDL.Float64),
  'systolic_latest' : IDL.Opt(IDL.Float64),
  'hr_avg_7d' : IDL.Opt(IDL.Float64),
  'consecutive_low_sleep_nights' : IDL.Nat,
  'hr_avg_14d' : IDL.Opt(IDL.Float64),
  'sleep_latest' : IDL.Opt(IDL.Float64),
  'sleep_avg_14d' : IDL.Opt(IDL.Float64),
  'diastolic_avg_7d' : IDL.Opt(IDL.Float64),
  'hr_latest' : IDL.Opt(IDL.Float64),
  'systolic_avg_14d' : IDL.Opt(IDL.Float64),
});
export const MetricSource = IDL.Variant({
  'Manual' : IDL.Null,
  'Bluetooth' : IDL.Null,
});
export const MetricType = IDL.Variant({
  'HeartRate' : IDL.Null,
  'DiastolicBP' : IDL.Null,
  'SystolicBP' : IDL.Null,
  'SleepHours' : IDL.Null,
});
export const HealthMetric = IDL.Record({
  'baseline_14d' : IDL.Opt(IDL.Float64),
  'value' : IDL.Float64,
  'source' : MetricSource,
  'metric_type' : MetricType,
  'user_id' : IDL.Text,
  'recorded_at' : IDL.Nat64,
});

export const idlService = IDL.Service({
  'add_metric' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Variant({ 'ok' : PredictionInput, 'err' : IDL.Text })],
      [],
    ),
  'get_prediction_input' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PredictionInput)],
      ['query'],
    ),
  'get_user_metrics' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Vec(HealthMetric)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PredictionInput = IDL.Record({
    'systolic_avg_7d' : IDL.Opt(IDL.Float64),
    'diastolic_latest' : IDL.Opt(IDL.Float64),
    'diastolic_avg_14d' : IDL.Opt(IDL.Float64),
    'sleep_avg_7d' : IDL.Opt(IDL.Float64),
    'systolic_latest' : IDL.Opt(IDL.Float64),
    'hr_avg_7d' : IDL.Opt(IDL.Float64),
    'consecutive_low_sleep_nights' : IDL.Nat,
    'hr_avg_14d' : IDL.Opt(IDL.Float64),
    'sleep_latest' : IDL.Opt(IDL.Float64),
    'sleep_avg_14d' : IDL.Opt(IDL.Float64),
    'diastolic_avg_7d' : IDL.Opt(IDL.Float64),
    'hr_latest' : IDL.Opt(IDL.Float64),
    'systolic_avg_14d' : IDL.Opt(IDL.Float64),
  });
  const MetricSource = IDL.Variant({
    'Manual' : IDL.Null,
    'Bluetooth' : IDL.Null,
  });
  const MetricType = IDL.Variant({
    'HeartRate' : IDL.Null,
    'DiastolicBP' : IDL.Null,
    'SystolicBP' : IDL.Null,
    'SleepHours' : IDL.Null,
  });
  const HealthMetric = IDL.Record({
    'baseline_14d' : IDL.Opt(IDL.Float64),
    'value' : IDL.Float64,
    'source' : MetricSource,
    'metric_type' : MetricType,
    'user_id' : IDL.Text,
    'recorded_at' : IDL.Nat64,
  });
  
  return IDL.Service({
    'add_metric' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Variant({ 'ok' : PredictionInput, 'err' : IDL.Text })],
        [],
      ),
    'get_prediction_input' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PredictionInput)],
        ['query'],
      ),
    'get_user_metrics' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Vec(HealthMetric)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };