/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HealthMetric {
  'baseline_14d' : [] | [number],
  'value' : number,
  'source' : MetricSource,
  'metric_type' : MetricType,
  'user_id' : string,
  'recorded_at' : bigint,
}
export type MetricSource = { 'Manual' : null } |
  { 'Bluetooth' : null };
export type MetricType = { 'HeartRate' : null } |
  { 'DiastolicBP' : null } |
  { 'SystolicBP' : null } |
  { 'SleepHours' : null };
export interface PredictionInput {
  'systolic_avg_7d' : [] | [number],
  'diastolic_latest' : [] | [number],
  'diastolic_avg_14d' : [] | [number],
  'sleep_avg_7d' : [] | [number],
  'systolic_latest' : [] | [number],
  'hr_avg_7d' : [] | [number],
  'consecutive_low_sleep_nights' : bigint,
  'hr_avg_14d' : [] | [number],
  'sleep_latest' : [] | [number],
  'sleep_avg_14d' : [] | [number],
  'diastolic_avg_7d' : [] | [number],
  'hr_latest' : [] | [number],
  'systolic_avg_14d' : [] | [number],
}
export interface _SERVICE {
  'add_metric' : ActorMethod<
    [string, string, number, string],
    { 'ok' : PredictionInput } |
      { 'err' : string }
  >,
  'get_prediction_input' : ActorMethod<[string], [] | [PredictionInput]>,
  'get_user_metrics' : ActorMethod<
    [string, bigint, [] | [string]],
    Array<HealthMetric>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];