/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PredictionInput {
    systolic_avg_7d?: number;
    diastolic_latest?: number;
    diastolic_avg_14d?: number;
    sleep_avg_7d?: number;
    systolic_latest?: number;
    hr_avg_7d?: number;
    consecutive_low_sleep_nights: bigint;
    hr_avg_14d?: number;
    sleep_latest?: number;
    sleep_avg_14d?: number;
    diastolic_avg_7d?: number;
    hr_latest?: number;
    systolic_avg_14d?: number;
}
export interface HealthMetric {
    baseline_14d?: number;
    value: number;
    source: MetricSource;
    metric_type: MetricType;
    user_id: string;
    recorded_at: bigint;
}
export enum MetricSource {
    Manual = "Manual",
    Bluetooth = "Bluetooth"
}
export enum MetricType {
    HeartRate = "HeartRate",
    DiastolicBP = "DiastolicBP",
    SystolicBP = "SystolicBP",
    SleepHours = "SleepHours"
}
export enum RegisterResult {
    ok = "ok",
    alreadyExists = "alreadyExists"
}
export enum VerifyResult {
    ok = "ok",
    wrongPassword = "wrongPassword",
    notFound = "notFound"
}
export interface backendInterface {
    add_metric(user_id: string, metric_type: string, value: number, source: string): Promise<{
        __kind__: "ok";
        ok: PredictionInput;
    } | {
        __kind__: "err";
        err: string;
    }>;
    get_prediction_input(user_id: string): Promise<PredictionInput | null>;
    get_user_metrics(user_id: string, past_days: bigint, metric_type_filter: string | null): Promise<Array<HealthMetric>>;
    registerUser(email: string, passwordHash: string): Promise<RegisterResult>;
    verifyPassword(email: string, passwordHash: string): Promise<VerifyResult>;
}
import type { HealthMetric as _HealthMetric, MetricSource as _MetricSource, MetricType as _MetricType, PredictionInput as _PredictionInput, RegisterResult as _RegisterResult, VerifyResult as _VerifyResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async add_metric(arg0: string, arg1: string, arg2: number, arg3: string): Promise<{
        __kind__: "ok";
        ok: PredictionInput;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.add_metric(arg0, arg1, arg2, arg3);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.add_metric(arg0, arg1, arg2, arg3);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_prediction_input(arg0: string): Promise<PredictionInput | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_prediction_input(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_prediction_input(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_user_metrics(arg0: string, arg1: bigint, arg2: string | null): Promise<Array<HealthMetric>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_user_metrics(arg0, arg1, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_user_metrics(arg0, arg1, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return from_candid_RegisterResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return from_candid_RegisterResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyPassword(arg0: string, arg1: string): Promise<VerifyResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPassword(arg0, arg1);
                return from_candid_VerifyResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPassword(arg0, arg1);
            return from_candid_VerifyResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_HealthMetric_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthMetric): HealthMetric {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_MetricSource_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetricSource): MetricSource {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_MetricType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetricType): MetricType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PredictionInput_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PredictionInput): PredictionInput {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_VerifyResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifyResult): VerifyResult {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PredictionInput]): PredictionInput | null {
    return value.length === 0 ? null : from_candid_PredictionInput_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    systolic_avg_7d: [] | [number];
    diastolic_latest: [] | [number];
    diastolic_avg_14d: [] | [number];
    sleep_avg_7d: [] | [number];
    systolic_latest: [] | [number];
    hr_avg_7d: [] | [number];
    consecutive_low_sleep_nights: bigint;
    hr_avg_14d: [] | [number];
    sleep_latest: [] | [number];
    sleep_avg_14d: [] | [number];
    diastolic_avg_7d: [] | [number];
    hr_latest: [] | [number];
    systolic_avg_14d: [] | [number];
}): {
    systolic_avg_7d?: number;
    diastolic_latest?: number;
    diastolic_avg_14d?: number;
    sleep_avg_7d?: number;
    systolic_latest?: number;
    hr_avg_7d?: number;
    consecutive_low_sleep_nights: bigint;
    hr_avg_14d?: number;
    sleep_latest?: number;
    sleep_avg_14d?: number;
    diastolic_avg_7d?: number;
    hr_latest?: number;
    systolic_avg_14d?: number;
} {
    return {
        systolic_avg_7d: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.systolic_avg_7d)),
        diastolic_latest: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.diastolic_latest)),
        diastolic_avg_14d: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.diastolic_avg_14d)),
        sleep_avg_7d: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.sleep_avg_7d)),
        systolic_latest: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.systolic_latest)),
        hr_avg_7d: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.hr_avg_7d)),
        consecutive_low_sleep_nights: value.consecutive_low_sleep_nights,
        hr_avg_14d: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.hr_avg_14d)),
        sleep_latest: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.sleep_latest)),
        sleep_avg_14d: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.sleep_avg_14d)),
        diastolic_avg_7d: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.diastolic_avg_7d)),
        hr_latest: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.hr_latest)),
        systolic_avg_14d: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.systolic_avg_14d))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    baseline_14d: [] | [number];
    value: number;
    source: _MetricSource;
    metric_type: _MetricType;
    user_id: string;
    recorded_at: bigint;
}): {
    baseline_14d?: number;
    value: number;
    source: MetricSource;
    metric_type: MetricType;
    user_id: string;
    recorded_at: bigint;
} {
    return {
        baseline_14d: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.baseline_14d)),
        value: value.value,
        source: from_candid_MetricSource_n10(_uploadFile, _downloadFile, value.source),
        metric_type: from_candid_MetricType_n12(_uploadFile, _downloadFile, value.metric_type),
        user_id: value.user_id,
        recorded_at: value.recorded_at
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PredictionInput;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PredictionInput;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PredictionInput_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Manual: null;
} | {
    Bluetooth: null;
}): MetricSource {
    return "Manual" in value ? MetricSource.Manual : "Bluetooth" in value ? MetricSource.Bluetooth : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HeartRate: null;
} | {
    DiastolicBP: null;
} | {
    SystolicBP: null;
} | {
    SleepHours: null;
}): MetricType {
    return "HeartRate" in value ? MetricType.HeartRate : "DiastolicBP" in value ? MetricType.DiastolicBP : "SystolicBP" in value ? MetricType.SystolicBP : "SleepHours" in value ? MetricType.SleepHours : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    alreadyExists: null;
}): RegisterResult {
    return "ok" in value ? RegisterResult.ok : "alreadyExists" in value ? RegisterResult.alreadyExists : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    wrongPassword: null;
} | {
    notFound: null;
}): VerifyResult {
    return "ok" in value ? VerifyResult.ok : "wrongPassword" in value ? VerifyResult.wrongPassword : "notFound" in value ? VerifyResult.notFound : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthMetric>): Array<HealthMetric> {
    return value.map((x)=>from_candid_HealthMetric_n8(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
